# Generated by Django 4.2.11 on 2024-04-02 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0003_alter_categories_options_alter_categories_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ("id",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукти",
            },
        ),
    ]
